config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
      self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name]) 	
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show	 
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
  	@books = Book.all
  end

  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	unless @book.save
	  	respond_to do |f|
	  		f.html { redirect_to books_url }
	  		f.js
	  	end
  	end

  end

  def update
  	unless @book.update(book_params)
	  	respond_to do |f|
	  		f.html { redirect_to books_url }
	  		f.js
	  	end  		

  	end 
  end

  def destroy
     @book.destroy
     respond_to do |f|
     	f.html { redirect_to books_url }
     	f.js
     end 
  end

  private 
    def set_book
    	@book = Book.find(params[:id])
    end

    def book_params
    	params.require(:book).permit(:name,:description,:author_name)
    end

    def admin_only
	    unless current_user.admin?
	      redirect_to root_path, :alert => "Access denied."
	    end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@books = Book.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<%= form_for book, remote: true do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :description %>
  <%= f.text_field :author_name%>
  <%= f.submit "Update" %>
  <%= link_to "(remove)", book, method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

app/views/books/_form.html.erb
<%= bootstrap_form_for @book, remote: true do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :description %>
  <%= f.text_field :author_name%>
  <%= f.submit %>
<% end %>

app/views/books/create.js.erb
$('#new_task').remove();
$('#new_link').show();
$('#incomplete_tasks').append('<%= j render(@book) %>')

app/views/books/destroy.js.erb
$('#edit_book_<%= @task.id %>').remove();

app/views/books/index.html.erb
<h1>List of books</h1>
<%= link_to "New Book", new_book_path, id: "new_link" %>
<h2>This book list</h2>
<div class="books" id="books_list">
  <%= render @books %>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render 'form' %>
<p><%= link_to "Back to books", books_path %></p>

app/views/books/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/books/update.js.erb
$('#edit_book_<%= @book.id %>').appendTo('#books_list');

app/views/home/index.html.erb
<div class="row">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Description</th>
              <th>Author</th>
            </tr>
          </thead>
          <tbody id="myTable">
          	<%= @books.each do |book|  %>
                <tr>
	              <td><%= book.id%></td>
	              <td><%= book.name%></td>
	              <td><%= book.description%></td>
	              <td><%= book.author_name%></td>
                </tr>
			     <% end %>
          </tbody>
        </table>   
      </div>
	</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%=root_path%>">My demo</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">User <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
              <% if current_user.try(:admin?) %>
                 <li><%= link_to 'Books list', books_path %></li>
              <% end %>
            </ul>
          </li>
      <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>     
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxCrud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar'%>
    <div class="container">
    	<%= yield %>
    </div>
  </body>
</html>